title: <p align="center"> Das Balvinder Das </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dasbalvinderdas/">LinkedIn</a> |
  <a href="https://github.com/DasBalvinderDas/">GitHub</a>
  
  <br>   
  I'm working on Google CLoud, Microservices, K8S, and learning AI & ML.
  Working with HCL Technologies.
  having 15+ years of industry experience.
  <br>
  </p>



theme: jekyll-theme-minimal
